/////////////////////////////////////////////////////////
/////////DO NOT MODIFY THIS AUTOGENERATED FILE///////////
///////////////////////////////////////////////////////// 
using System;
using System.Collections.Generic;

// ReSharper disable InconsistentNaming
namespace Peak.QuixelLogic.Scripts.Autogenerated
{
    [Serializable]
    public enum GameWindow
    {
        NoWindow = 0,
        GlobalLogic = 1,
        LoadingMenu = 2,
        StartGame = 3,
        BoardBlur = 4,
        BoardMenu = 5,
        BoardUI = 6,
        BonusBarUI = 7,
        CollectionOverlay = 8,
        CollectionScreen = 9,
        IntroVideo = 10,
        MainMenu = 11,
        OverlayUIScene = 12,
        PostGameScene = 13,
        SettingsMenuUI = 14,
        StoreUI = 15,
        ToolbarUI = 16,
        TopBarUI = 17,
        UICoinCounter = 18,
        UIFilmCounter = 19,
        UILevelProgressCounter = 20,
        PopUpAndroidGold = 21,
        PopUpAndroidReview = 22,
        PopUpFilm = 23,
        PopUpGdpr = 24,
        PopUpNotifications = 25,
        PopupClaimCoins = 26,
        PopupGameComplete = 27,
        PopupGoldLevelPurchase = 28,
        PopupReplayLevel = 29,
        PopupRewardedVideo = 30,
        PopupStoreMessage = 31,
    }

    public static class GameWindowNames
    {
        public static readonly Dictionary<GameWindow, string> Mapping = new Dictionary<GameWindow, string>
        {
             { GameWindow.NoWindow, string.Empty },
             { GameWindow.GlobalLogic , "GlobalLogic" },
             { GameWindow.LoadingMenu , "LoadingMenu" },
             { GameWindow.StartGame , "StartGame" },
             { GameWindow.BoardBlur , "BoardBlur" },
             { GameWindow.BoardMenu , "BoardMenu" },
             { GameWindow.BoardUI , "BoardUI" },
             { GameWindow.BonusBarUI , "BonusBarUI" },
             { GameWindow.CollectionOverlay , "CollectionOverlay" },
             { GameWindow.CollectionScreen , "CollectionScreen" },
             { GameWindow.IntroVideo , "IntroVideo" },
             { GameWindow.MainMenu , "MainMenu" },
             { GameWindow.OverlayUIScene , "OverlayUIScene" },
             { GameWindow.PostGameScene , "PostGameScene" },
             { GameWindow.SettingsMenuUI , "SettingsMenuUI" },
             { GameWindow.StoreUI , "StoreUI" },
             { GameWindow.ToolbarUI , "ToolbarUI" },
             { GameWindow.TopBarUI , "TopBarUI" },
             { GameWindow.UICoinCounter , "UICoinCounter" },
             { GameWindow.UIFilmCounter , "UIFilmCounter" },
             { GameWindow.UILevelProgressCounter , "UILevelProgressCounter" },
             { GameWindow.PopUpAndroidGold , "PopUpAndroidGold" },
             { GameWindow.PopUpAndroidReview , "PopUpAndroidReview" },
             { GameWindow.PopUpFilm , "PopUpFilm" },
             { GameWindow.PopUpGdpr , "PopUpGdpr" },
             { GameWindow.PopUpNotifications , "PopUpNotifications" },
             { GameWindow.PopupClaimCoins , "PopupClaimCoins" },
             { GameWindow.PopupGameComplete , "PopupGameComplete" },
             { GameWindow.PopupGoldLevelPurchase , "PopupGoldLevelPurchase" },
             { GameWindow.PopupReplayLevel , "PopupReplayLevel" },
             { GameWindow.PopupRewardedVideo , "PopupRewardedVideo" },
             { GameWindow.PopupStoreMessage , "PopupStoreMessage" },
        };
    }
}