using System.Collections;
using System.Collections.Generic;
using Peak.UnityGameFramework.Scripts.ScenesLogic;
using Peak.UnityGameFramework.Scripts.Settings.Autogenerated;
using UnityEngine;

namespace Peak.UnityGameFramework.Scripts.Common
{
    public class RoundAnimationScript : MonoBehaviour
    {
        public void PlayRoundCorrectSound()
        {
            LocalisationController.Instance.PlayAudioClip(SoundSettingsKey.GUICorrect);
        }

        public void PlayRoundWrongSound()
        {
            LocalisationController.Instance.PlayAudioClip(SoundSettingsKey.GUIWrong);
        }

        public void CorrectRoundCompleteHandler()
        {
            SceneActivationBehaviour<OverlayUISceneActivator>.Instance.CorrectAnimationDone();
        }

        public void WrongRoundCompleteHandler()
        {
            SceneActivationBehaviour<OverlayUISceneActivator>.Instance.WrongAnimationDone();
        }
    }
}
