using System.Collections;
using System.Collections.Generic;
using Peak.Speedoku.Scripts.ScenesLogic;
using UnityEngine;

namespace Peak.Speedoku.Scripts.Common.AnimationEvents
{
    public class MainMenuAnimationEvents : MonoBehaviour
    {
        public void StartGameAnimationGridActiveHandler()
        {
            SceneActivationBehaviour<MainMenuActivator>.Instance.SetupGame();
        }

        public void StartGameAnimationFinishedHandler()
        {
            SceneActivationBehaviour<MainMenuActivator>.Instance.StartGame();
        }

        //public void SetupProgressBar()
        //{
        //    SceneActivationBehaviour<MainMenuActivator>.Instance.SetupProgressBar();
        //}

        public void UpdateProgressBar()
        {
            SceneActivationBehaviour<MainMenuActivator>.Instance.UpdateProgressBar();
        }

        public void ExitGameAnimationFinishedHandler()
        {
            SceneActivationBehaviour<MainMenuActivator>.Instance.GameFinishedAnimationOver();
        }

        public void PlayQuestionMarkSound()
        {
            LocalisationController.Instance.PlayAudioClip(Settings.Autogenerated.SoundSettingsKey.PopupSound);
        }

        public void PlayGridSlideSound()
        {
            LocalisationController.Instance.PlayAudioClip(Settings.Autogenerated.SoundSettingsKey.BoardAppear);
        }
    }
}
