using System.Collections;
using System.Collections.Generic;
using Peak.Speedoku.Scripts.Settings.Autogenerated;
using UnityEngine;

namespace Peak.Speedoku.Scripts.Common
{
    public class CheckBoxController : MonoBehaviour
    {
        [SerializeField] private GameObject tickImage;
        [SerializeField] private GameObject crossImage;
        [SerializeField] private Animator checkBoxAnimator;

        private SoundSettingsKey sound;

        public void SetupWithAnswer(bool correct)
        {
            tickImage.SetActive(correct);
            crossImage.SetActive(!correct);
            sound = correct ? SoundSettingsKey.LevelNumberUpdate : SoundSettingsKey.CrossAppears;
            checkBoxAnimator.Rebind();
        }

        public void StartAnimation()
        {
            checkBoxAnimator.SetTrigger(Constants.Animation.CheckBox.ShowAnswer);
        }

        public void PlaySound()
        {
            LocalisationController.Instance.PlayAudioClip(sound);
#if PLATFORM_IOS
            iOSHapticFeedbackHelper.OnSelection();
#endif
        }
    }
}
