using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Peak.Speedoku.Scripts.Settings.Autogenerated;
using Peak.Speedoku.Scripts.ScenesLogic;
using Peak.Speedoku.Scripts.Common;
using Peak.Speedoku.Scripts.Autogenerated;
using JetBrains.Annotations;
using System.Linq;

namespace Peak.Speedoku.Scripts.Common
{
    public class InputController : MonoBehaviour
    {
        [UsedImplicitly]
        private void Awake()
        {
            Application.targetFrameRate = 60;
        }

        public void Initialise()
        {
            //print("[   ] Initialising input controller ");
        }



    }
}


