using System;
using System.Collections;
using System.Collections.Generic;
using Peak.QuixelLogic.Scripts.Autogenerated;
using Peak.QuixelLogic.Scripts.Common;
using Peak.QuixelLogic.Scripts.Game.Gameplay;
using Peak.QuixelLogic.Scripts.ScenesLogic;
using Peak.QuixelLogic.Scripts.Settings;
using UnityEngine;

namespace Peak.QuixelLogic.Scripts.Game.FtueGameplay
{
    public class FtueGame_2 : MonoBehaviour
    {
        public void StartGame(Player player,
                                      RuleSettings selectedRuleset,
                                      FtueController ftueController,
                                      SessionScript sessionScript,
                                      OverlayUISceneActivator overlayUISceneActivator)
        {
            print("[FTUE] Second ftue game started ");

            InterfaceController.Instance.Show(GameWindow.OverlayUIScene);
            InterfaceController.Instance.Hide(GameWindow.MainMenu);

            SceneActivationBehaviour<TopBarUIActivator>.Instance.SetButtons(false);

            InterfaceController.Instance.Hide(GameWindow.ToolbarUI);

            GameplayScript gameplay = sessionScript.CreateGameAndStart(player, selectedRuleset);
            BoardCreationScript boardCreationScript = gameplay.GetComponent<BoardCreationScript>();
            GridLabelManager gridLabelManager = boardCreationScript.gameObject.GetComponent<GridLabelManager>();

            boardCreationScript.BlockAllCells();

            overlayUISceneActivator.ShowFtueGameplayMessage(GameConstants.Ftue.SecondGame.FtueMessages.Instructions2_0, true, true, 0, true);

            ftueController.SendFtueProgress("Game2LetsFind_10");

            overlayUISceneActivator.SubscribeForFullScreenTap(() =>
            {
                ftueController.SendFtueProgress("RememberBig_11");
                overlayUISceneActivator.ShowFtueGameplayMessage(GameConstants.Ftue.SecondGame.FtueMessages.Instructions2_1, true);

                gridLabelManager.ShowFtueArrows(new List<int> { 6 });
                gridLabelManager.ShowSpecificGridLabelsOnFtue(new List<int> { 1 }, new List<int> { });

                boardCreationScript.HighlightCells(true, GameConstants.Ftue.SecondGame.DimAnimations.Dim2_1);

                boardCreationScript.BlockCellsToBeSelected(GameConstants.Ftue.SecondGame.TargetCellVectors.TargetCells2_1);
                ftueController.ListenForCurrentFtueCellSelection(gameplay, GameConstants.Ftue.SecondGame.TargetCellVectors.TargetCells2_1, () =>
                {
                    overlayUISceneActivator.HideFtueMessages();

                }, () =>
                {
                    ftueController.SendFtueProgress("GreatKeepGoing_12");
                    overlayUISceneActivator.ShowFtueGameplayMessage(GameConstants.Ftue.SecondGame.FtueMessages.Instructions2_2, true);

                    gridLabelManager.ShowFtueArrows(new List<int> { 1, 3 });
                    gridLabelManager.ShowSpecificGridLabelsOnFtue(new List<int> { 1 }, new List<int> { 1, 3 });

                    boardCreationScript.HighlightCells(true, GameConstants.Ftue.SecondGame.DimAnimations.Dim2_2);

                    boardCreationScript.BlockCellsToBeSelected(GameConstants.Ftue.SecondGame.TargetCellVectors.TargetCells2_2);

                    ftueController.ListenForFirstSpecificSelection(gameplay, new List<Vector2> { new Vector2(1, 2), new Vector2(3, 2), new Vector2(4, 2), new Vector2(5, 2) }, () =>
                    {
                        gridLabelManager.HideSpecificFtueArrow(1);
                    });

                    ftueController.ListenForSecondSpecificSelection(gameplay, new List<Vector2> { new Vector2(1, 4), new Vector2(3, 4), new Vector2(4, 4), new Vector2(5, 4) }, () =>
                    {
                        gridLabelManager.HideSpecificFtueArrow(3);
                    });

                    ftueController.ListenForCurrentFtueCellSelection(gameplay, GameConstants.Ftue.SecondGame.TargetCellVectors.TargetCells2_2, () =>
                    {
                        overlayUISceneActivator.HideFtueMessages();

                    }, () =>
                    {
                        ftueController.SendFtueProgress("TwoAndTwo_13");
                        overlayUISceneActivator.ShowFtueGameplayMessage(GameConstants.Ftue.SecondGame.FtueMessages.Instructions2_3, true);

                        gridLabelManager.ShowFtueArrows(new List<int> { 5 });
                        gridLabelManager.ShowSpecificGridLabelsOnFtue(new List<int> { 0, 1 }, new List<int> { 0, 1, 3, 4 });

                        boardCreationScript.HighlightCells(true, GameConstants.Ftue.SecondGame.DimAnimations.Dim2_3);

                        boardCreationScript.BlockCellsToBeSelected(GameConstants.Ftue.SecondGame.TargetCellVectors.TargetCells2_3);
                        ftueController.ListenForCurrentFtueCellSelection(gameplay, GameConstants.Ftue.SecondGame.TargetCellVectors.TargetCells2_3, () =>
                        {
                            overlayUISceneActivator.HideFtueMessages();

                        }, () =>
                        {
                            ftueController.SendFtueProgress("GroupThree_14");
                            overlayUISceneActivator.ShowFtueGameplayMessage(GameConstants.Ftue.SecondGame.FtueMessages.Instructions2_4, true);

                            gridLabelManager.ShowFtueArrows(new List<int> { 7 });
                            gridLabelManager.ShowSpecificGridLabelsOnFtue(new List<int> { 0, 1, 2 }, new List<int> { 0, 1, 3, 4 });

                            boardCreationScript.HighlightCells(true, GameConstants.Ftue.SecondGame.DimAnimations.Dim2_4);

                            boardCreationScript.BlockCellsToBeSelected(GameConstants.Ftue.SecondGame.TargetCellVectors.TargetCells2_4);
                            ftueController.ListenForCurrentFtueCellSelection(gameplay, GameConstants.Ftue.SecondGame.TargetCellVectors.TargetCells2_4, () =>
                            {
                                overlayUISceneActivator.HideFtueMessages();

                            }, () =>
                            {
                                ftueController.SendFtueProgress("ThreeAdjacents_15");
                                overlayUISceneActivator.ShowFtueGameplayMessage(GameConstants.Ftue.SecondGame.FtueMessages.Instructions2_5, true);

                                gridLabelManager.ShowFtueArrows(new List<int> { 8, 9 });
                                gridLabelManager.ShowSpecificGridLabelsOnFtue(new List<int> { 0, 1, 2, 3, 4 }, new List<int> { 0, 1, 2, 3, 4 });

                                boardCreationScript.HighlightCells(true, GameConstants.Ftue.SecondGame.DimAnimations.Dim2_5);

                                ftueController.ListenForFirstSpecificSelection(gameplay, new List<Vector2> { new Vector2(4, 3) }, () =>
                                 {
                                     gridLabelManager.HideSpecificFtueArrow(8);
                                 });

                                ftueController.ListenForSecondSpecificSelection(gameplay, new List<Vector2> { new Vector2(5, 3) }, () =>
                                {
                                    gridLabelManager.HideSpecificFtueArrow(9);
                                });

                                boardCreationScript.BlockCellsToBeSelected(GameConstants.Ftue.SecondGame.TargetCellVectors.TargetCells2_5, false);
                                ftueController.ListenForCurrentFtueCellSelection(gameplay, GameConstants.Ftue.SecondGame.TargetCellVectors.TargetCells2_5, () =>
                                {
                                    overlayUISceneActivator.HideFtueMessages();

                                }, () =>
                                {
                                    boardCreationScript.HighlightCells(false);

                                    overlayUISceneActivator.ftueMessagesPerStage = 0;
                                    gameplay.StartDelayedSession();

                                    gameplay.OnPuzzleSolved += gameData =>
                                    {
                                        overlayUISceneActivator.HideFtueMessages();

                                        int i = int.Parse(gameData.Ruleset.Id);
                                        ftueController.ProceedToGameOverAward(player, i);

                                        ftueController.SendFtueProgress("Game2Complete_16");
                                    };
                                });
                            });
                        });
                    });
                });
            });
        }
    }
}