using System;
using System.Collections;
using System.Collections.Generic;
using Peak.QuixelLogic.Scripts.Autogenerated;
using Peak.QuixelLogic.Scripts.Common;
using Peak.QuixelLogic.Scripts.Game.Gameplay;
using Peak.QuixelLogic.Scripts.ScenesLogic;
using Peak.QuixelLogic.Scripts.Settings;
using UnityEngine;

namespace Peak.QuixelLogic.Scripts.Game.FtueGameplay
{
    public class FtueGame_1 : MonoBehaviour
    {
        public void StartGame(Player player,
                              RuleSettings selectedRuleset,
                              FtueController ftueController,
                              SessionScript sessionScript,
                              OverlayUISceneActivator overlayUISceneActivator)
        {
            print("[FTUE] First ftue game started " + overlayUISceneActivator.name);

            InterfaceController.Instance.Show(GameWindow.OverlayUIScene);
            InterfaceController.Instance.Hide(GameWindow.MainMenu);

            SceneActivationBehaviour<TopBarUIActivator>.Instance.SetButtons(false);

            InterfaceController.Instance.Hide(GameWindow.ToolbarUI);

            GameplayScript gameplay = sessionScript.CreateGameAndStart(player, selectedRuleset);
            BoardCreationScript boardCreationScript = gameplay.GetComponent<BoardCreationScript>();
            GridLabelManager gridLabelManager = boardCreationScript.gameObject.GetComponent<GridLabelManager>();

            boardCreationScript.BlockAllCells();

            overlayUISceneActivator.ShowFtueGameplayMessage(GameConstants.Ftue.FirstGame.FtueMessages.Instructions1_1, true, true, 0, true);

            ftueController.SendFtueProgress("Game1TheGoal_1");

            overlayUISceneActivator.SubscribeForFullScreenTap(() =>
            {
                ftueController.SendFtueProgress("FiveAdjacent_2");
                overlayUISceneActivator.ShowFtueGameplayMessage(GameConstants.Ftue.FirstGame.FtueMessages.Instructions1_2, true);

                gridLabelManager.ShowSpecificGridLabelsOnFtue(new List<int> { 1 }, new List<int> { });
                gridLabelManager.ShowFtueArrows(new List<int> { 6 });

                boardCreationScript.HighlightCells(true, GameConstants.Ftue.FirstGame.DimAnimations.Dim1_2);
                SceneActivationBehaviour<OverlayUISceneActivator>.Instance.ShowHandAnimation(true, GameConstants.Ftue.FirstGame.HandAnimations.Hand1_2);

                boardCreationScript.BlockCellsToBeSelected(GameConstants.Ftue.FirstGame.TargetCellVectors.TargetCells1_2);
                ftueController.ListenForCurrentFtueCellSelection(gameplay, GameConstants.Ftue.FirstGame.TargetCellVectors.TargetCells1_2, () =>
                {
                    SceneActivationBehaviour<OverlayUISceneActivator>.Instance.ShowHandAnimation(false);
                    overlayUISceneActivator.HideFtueMessages();

                }, () =>
                {
                    ftueController.SendFtueProgress("FiveTiles_3");
                    overlayUISceneActivator.ShowFtueGameplayMessage(GameConstants.Ftue.FirstGame.FtueMessages.Instructions1_3, true);

                    boardCreationScript.HighlightCells(true, GameConstants.Ftue.FirstGame.DimAnimations.Dim1_3);

                    gridLabelManager.ShowSpecificGridLabelsOnFtue(new List<int> { 1 }, new List<int> { 2 });
                    gridLabelManager.ShowFtueArrows(new List<int> { 2 });

                    SceneActivationBehaviour<OverlayUISceneActivator>.Instance.ShowHandAnimation(true, GameConstants.Ftue.FirstGame.HandAnimations.Hand1_3);

                    boardCreationScript.BlockCellsToBeSelected(GameConstants.Ftue.FirstGame.TargetCellVectors.TargetCells1_3);
                    ftueController.ListenForCurrentFtueCellSelection(gameplay, GameConstants.Ftue.FirstGame.TargetCellVectors.TargetCells1_3, () =>
                    {
                        SceneActivationBehaviour<OverlayUISceneActivator>.Instance.ShowHandAnimation(false);
                        overlayUISceneActivator.HideFtueMessages();
                    }, () =>
                    {
                        ftueController.SendFtueProgress("FoundSingle_4");
                        overlayUISceneActivator.ShowFtueGameplayMessage(GameConstants.Ftue.FirstGame.FtueMessages.Instructions1_4, true, true, 0, true);

                        gridLabelManager.ShowSpecificGridLabelsOnFtue(new List<int> { 1, 4 }, new List<int> { 2 });
                        gridLabelManager.ShowFtueArrows(new List<int> { 9 });

                        boardCreationScript.HighlightCells(true, GameConstants.Ftue.FirstGame.DimAnimations.Dim1_4);

                        overlayUISceneActivator.SubscribeForFullScreenTap(() =>
                        {
                            ftueController.SendFtueProgress("BigNumbers_5");
                            overlayUISceneActivator.ShowFtueGameplayMessage(GameConstants.Ftue.FirstGame.FtueMessages.Instructions1_5, true);

                            gridLabelManager.ShowSpecificGridLabelsOnFtue(new List<int> { 1, 2, 3, 4 }, new List<int> { 0, 2, 4 });
                            gridLabelManager.ShowFtueArrows(new List<int> { 7, 8 });

                            SceneActivationBehaviour<OverlayUISceneActivator>.Instance.ShowHandAnimation(true, GameConstants.Ftue.FirstGame.HandAnimations.Hand1_5);

                            boardCreationScript.HighlightCells(true, GameConstants.Ftue.FirstGame.DimAnimations.Dim1_5);

                            boardCreationScript.BlockCellsToBeSelected(GameConstants.Ftue.FirstGame.TargetCellVectors.TargetCells1_5);

                            ftueController.ListenForFirstSpecificSelection(gameplay, new List<Vector2> { new Vector2(3, 1), new Vector2(3, 2), new Vector2(3, 4), new Vector2(3, 5) }, () =>
                            {
                                gridLabelManager.HideSpecificFtueArrow(7);
                            });

                            ftueController.ListenForSecondSpecificSelection(gameplay, new List<Vector2> { new Vector2(4, 1), new Vector2(4, 2), new Vector2(4, 4), new Vector2(4, 5) }, () =>
                            {
                                gridLabelManager.HideSpecificFtueArrow(8);
                            });

                            ftueController.ListenForCurrentFtueCellSelection(gameplay, GameConstants.Ftue.FirstGame.TargetCellVectors.TargetCells1_5, () =>
                            {
                                overlayUISceneActivator.HideFtueMessages();
                                SceneActivationBehaviour<OverlayUISceneActivator>.Instance.ShowHandAnimation(false);
                            }, () =>
                            {
                                ftueController.SendFtueProgress("OneTileSo_6");
                                overlayUISceneActivator.ShowFtueGameplayMessage(GameConstants.Ftue.FirstGame.FtueMessages.Instructions1_6, true, true, 0, true);

                                boardCreationScript.HighlightCells(true, GameConstants.Ftue.FirstGame.DimAnimations.Dim1_6);
                                gridLabelManager.ShowFtueArrows(new List<int> { 9 });

                                overlayUISceneActivator.SubscribeForFullScreenTap(() =>
                                {
                                    ftueController.SendFtueProgress("FourAdjacent_7");
                                    overlayUISceneActivator.ShowFtueGameplayMessage(GameConstants.Ftue.FirstGame.FtueMessages.Instructions1_7, true);

                                    boardCreationScript.HighlightCells(true, GameConstants.Ftue.FirstGame.DimAnimations.Dim1_7);

                                    gridLabelManager.ShowSpecificGridLabelsOnFtue(new List<int> { 1, 2, 3, 4 }, new List<int> { 0, 1, 2, 4 });
                                    gridLabelManager.ShowFtueArrows(new List<int> { 1 });

                                    SceneActivationBehaviour<OverlayUISceneActivator>.Instance.ShowHandAnimation(true, GameConstants.Ftue.FirstGame.HandAnimations.Hand1_7);

                                    boardCreationScript.BlockCellsToBeSelected(GameConstants.Ftue.FirstGame.TargetCellVectors.TargetCells1_7);
                                    ftueController.ListenForCurrentFtueCellSelection(gameplay, GameConstants.Ftue.FirstGame.TargetCellVectors.TargetCells1_7, () =>
                                    {
                                        overlayUISceneActivator.HideFtueMessages();
                                        SceneActivationBehaviour<OverlayUISceneActivator>.Instance.ShowHandAnimation(false);
                                    }, () =>
                                    {
                                        ftueController.SendFtueProgress("CanYouFind_8");
                                        overlayUISceneActivator.ShowFtueGameplayMessage(GameConstants.Ftue.FirstGame.FtueMessages.Instructions1_8, true);

                                        gridLabelManager.ShowSpecificGridLabelsOnFtue(new List<int> { 0, 1, 2, 3, 4 }, new List<int> { 0, 1, 2, 3, 4 });
                                        gridLabelManager.ShowFtueArrows(new List<int> { 3 });

                                        boardCreationScript.HighlightCells(true, GameConstants.Ftue.FirstGame.DimAnimations.Dim1_8);

                                        boardCreationScript.BlockCellsToBeSelected(GameConstants.Ftue.FirstGame.TargetCellVectors.TargetCells1_8, false);
                                        ftueController.ListenForCurrentFtueCellSelection(gameplay, GameConstants.Ftue.FirstGame.TargetCellVectors.TargetCells1_8, () =>
                                        {
                                            overlayUISceneActivator.HideFtueMessages();
                                            boardCreationScript.HighlightCells(false);
                                        }, () =>
                                        {
                                            overlayUISceneActivator.ftueMessagesPerStage = 0;
                                            gameplay.StartDelayedSession();

                                            gameplay.OnPuzzleSolved += gameData =>
                                            {
                                                overlayUISceneActivator.HideFtueMessages();

                                                int i = int.Parse(gameData.Ruleset.Id);
                                                ftueController.ProceedToGameOverAward(player, i);

                                                ftueController.SendFtueProgress("Game1Complete_9");
                                            };
                                        });
                                    });
                                });
                            });
                        });
                    });
                });
            });
        }
    }
}