using System;
using System.Collections;
using System.Collections.Generic;
using Peak.QuixelLogic.Scripts.Autogenerated;
using Peak.QuixelLogic.Scripts.Common;
using Peak.QuixelLogic.Scripts.Game.Gameplay;
using Peak.QuixelLogic.Scripts.ScenesLogic;
using Peak.QuixelLogic.Scripts.Settings;
using UnityEngine;

namespace Peak.QuixelLogic.Scripts.Game.FtueGameplay
{
    public class FtueGame_3 : MonoBehaviour
    {
        public void StartGame(Player player,
                                          RuleSettings selectedRuleset,
                                          FtueController ftueController,
                                          SessionScript sessionScript,
                                          OverlayUISceneActivator overlayUISceneActivator)
        {
            print("[FTUE] Third ftue game started ");

            InterfaceController.Instance.Show(GameWindow.OverlayUIScene);
            InterfaceController.Instance.Hide(GameWindow.MainMenu);

            SceneActivationBehaviour<TopBarUIActivator>.Instance.SetButtons(false);

            InterfaceController.Instance.Hide(GameWindow.ToolbarUI);

            GameplayScript gameplay = sessionScript.CreateGameAndStart(player, selectedRuleset);
            BoardCreationScript boardCreationScript = gameplay.GetComponent<BoardCreationScript>();
            GridLabelManager gridLabelManager = boardCreationScript.gameObject.GetComponent<GridLabelManager>();

            boardCreationScript.BlockAllCells();

            overlayUISceneActivator.ShowFtueGameplayMessage(GameConstants.Ftue.ThirdGame.FtueMessages.Instructions3_0, true, true, 0, true);

            ftueController.SendFtueProgress("Game3LetsLearn_17");

            overlayUISceneActivator.SubscribeForFullScreenTap(() =>
            {
                ftueController.SendFtueProgress("BigNumbers_18");
                overlayUISceneActivator.ShowFtueGameplayMessage(GameConstants.Ftue.ThirdGame.FtueMessages.Instructions3_1, true);

                gridLabelManager.ShowFtueArrows(new List<int> { 6 });
                gridLabelManager.ShowSpecificGridLabelsOnFtue(new List<int> { 1 }, new List<int> { });

                boardCreationScript.HighlightCells(true, GameConstants.Ftue.ThirdGame.DimAnimations.Dim3_1);

                boardCreationScript.BlockCellsToBeSelected(GameConstants.Ftue.ThirdGame.TargetCellVectors.TargetCells3_1);
                ftueController.ListenForCurrentFtueCellSelection(gameplay, GameConstants.Ftue.ThirdGame.TargetCellVectors.TargetCells3_1, () =>
                {
                    overlayUISceneActivator.HideFtueMessages();
                }, () =>
                {
                    ftueController.SendFtueProgress("FiveConnected_19");
                    overlayUISceneActivator.ShowFtueGameplayMessage(GameConstants.Ftue.ThirdGame.FtueMessages.Instructions3_2, true);

                    gridLabelManager.ShowFtueArrows(new List<int> { 9 });
                    gridLabelManager.ShowSpecificGridLabelsOnFtue(new List<int> { 1, 4 }, new List<int> { });

                    boardCreationScript.HighlightCells(true, GameConstants.Ftue.ThirdGame.DimAnimations.Dim3_2);

                    boardCreationScript.BlockCellsToBeSelected(GameConstants.Ftue.ThirdGame.TargetCellVectors.TargetCells3_2);
                    ftueController.ListenForCurrentFtueCellSelection(gameplay, GameConstants.Ftue.ThirdGame.TargetCellVectors.TargetCells3_2, () =>
                    {
                        overlayUISceneActivator.HideFtueMessages();
                    }, () =>
                    {
                        ftueController.SendFtueProgress("FourConnected_20");
                        overlayUISceneActivator.ShowFtueGameplayMessage(GameConstants.Ftue.ThirdGame.FtueMessages.Instructions3_3, true);

                        gridLabelManager.ShowFtueArrows(new List<int> { 1 });
                        gridLabelManager.ShowSpecificGridLabelsOnFtue(new List<int> { 1, 4 }, new List<int> { 1 });

                        boardCreationScript.HighlightCells(true, GameConstants.Ftue.ThirdGame.DimAnimations.Dim3_3);

                        boardCreationScript.BlockCellsToBeSelected(GameConstants.Ftue.ThirdGame.TargetCellVectors.TargetCells3_3);
                        ftueController.ListenForCurrentFtueCellSelection(gameplay, GameConstants.Ftue.ThirdGame.TargetCellVectors.TargetCells3_3, () =>
                        {
                            overlayUISceneActivator.HideFtueMessages();
                        }, () =>
                        {
                            ftueController.SendFtueProgress("WhatTiles_21");
                            overlayUISceneActivator.ShowFtueGameplayMessage(GameConstants.Ftue.ThirdGame.FtueMessages.Instructions3_4, true);

                            gridLabelManager.ShowFtueArrows(new List<int> { 3 });
                            gridLabelManager.ShowSpecificGridLabelsOnFtue(new List<int> { 1, 3, 4 }, new List<int> { 1, 3 });

                            boardCreationScript.HighlightCells(true, GameConstants.Ftue.ThirdGame.DimAnimations.Dim3_4);

                            boardCreationScript.BlockCellsToBeSelected(GameConstants.Ftue.ThirdGame.TargetCellVectors.TargetCells3_4, false);
                            ftueController.ListenForCurrentFtueCellSelection(gameplay, GameConstants.Ftue.ThirdGame.TargetCellVectors.TargetCells3_4, () =>
                            {
                                overlayUISceneActivator.HideFtueMessages();
                            }, () =>
                            {
                                ftueController.SendFtueProgress("SeveralDigits_22");
                                overlayUISceneActivator.ShowFtueGameplayMessage(GameConstants.Ftue.ThirdGame.FtueMessages.Instructions3_5, true);

                                gridLabelManager.ShowFtueArrows(new List<int> { 0 });
                                gridLabelManager.ShowSpecificGridLabelsOnFtue(new List<int> { 1, 2, 3, 4 }, new List<int> { 0, 1, 3 });

                                boardCreationScript.HighlightCells(true, GameConstants.Ftue.ThirdGame.DimAnimations.Dim3_5);

                                boardCreationScript.BlockCellsToBeSelected(GameConstants.Ftue.ThirdGame.TargetCellVectors.TargetCells3_5);
                                ftueController.ListenForCurrentFtueCellSelection(gameplay, GameConstants.Ftue.ThirdGame.TargetCellVectors.TargetCells3_5, () =>
                                {
                                    overlayUISceneActivator.HideFtueMessages();
                                }, () =>
                                {
                                    ftueController.SendFtueProgress("TwoAndOne_23");
                                    overlayUISceneActivator.ShowFtueGameplayMessage(GameConstants.Ftue.ThirdGame.FtueMessages.Instructions3_6, true);

                                    gridLabelManager.ShowFtueArrows(new List<int> { 4 });
                                    gridLabelManager.ShowSpecificGridLabelsOnFtue(new List<int> { 1, 2, 3, 4 }, new List<int> { 0, 1, 3, 4 });

                                    boardCreationScript.HighlightCells(true, GameConstants.Ftue.ThirdGame.DimAnimations.Dim3_6);

                                    boardCreationScript.BlockCellsToBeSelected(GameConstants.Ftue.ThirdGame.TargetCellVectors.TargetCells3_6);
                                    ftueController.ListenForCurrentFtueCellSelection(gameplay, GameConstants.Ftue.ThirdGame.TargetCellVectors.TargetCells3_6, () =>
                                    {
                                        overlayUISceneActivator.HideFtueMessages();
                                    }, () =>
                                    {
                                        ftueController.SendFtueProgress("ThreeSeparate_24");
                                        overlayUISceneActivator.ShowFtueGameplayMessage(GameConstants.Ftue.ThirdGame.FtueMessages.Instructions3_7, true);

                                        gridLabelManager.ShowFtueArrows(new List<int> { 5 });
                                        gridLabelManager.ShowSpecificGridLabelsOnFtue(new List<int> { 0, 1, 2, 3, 4 }, new List<int> { 0, 1, 3, 4 });

                                        boardCreationScript.HighlightCells(true, GameConstants.Ftue.ThirdGame.DimAnimations.Dim3_7);

                                        boardCreationScript.BlockCellsToBeSelected(GameConstants.Ftue.ThirdGame.TargetCellVectors.TargetCells3_7);
                                        ftueController.ListenForCurrentFtueCellSelection(gameplay, GameConstants.Ftue.ThirdGame.TargetCellVectors.TargetCells3_7, () =>
                                        {
                                            overlayUISceneActivator.HideFtueMessages();
                                        }, () =>
                                        {
                                            ftueController.SendFtueProgress("CompleteColumn_25");
                                            overlayUISceneActivator.ShowFtueGameplayMessage(GameConstants.Ftue.ThirdGame.FtueMessages.Instructions3_8, true);

                                            gridLabelManager.ShowFtueArrows(new List<int> { 2 });
                                            gridLabelManager.ShowSpecificGridLabelsOnFtue(new List<int> { 0, 1, 2, 3, 4 }, new List<int> { 0, 1, 2, 3, 4 });

                                            boardCreationScript.HighlightCells(true, GameConstants.Ftue.ThirdGame.DimAnimations.Dim3_8);

                                            boardCreationScript.BlockCellsToBeSelected(GameConstants.Ftue.ThirdGame.TargetCellVectors.TargetCells3_8, false);
                                            ftueController.ListenForCurrentFtueCellSelection(gameplay, GameConstants.Ftue.ThirdGame.TargetCellVectors.TargetCells3_8, () =>
                                            {
                                                overlayUISceneActivator.HideFtueMessages();
                                                boardCreationScript.HighlightCells(false);
                                            }, () =>
                                            {
                                                overlayUISceneActivator.ftueMessagesPerStage = 0;
                                                gameplay.StartDelayedSession();

                                                gameplay.OnPuzzleSolved += gameData =>
                                                {
                                                    overlayUISceneActivator.HideFtueMessages();

                                                    int i = int.Parse(gameData.Ruleset.Id);
                                                    ftueController.ProceedToGameOverAward(player, i);

                                                    ftueController.SendFtueProgress("Game3Complete_26");
                                                };
                                            });
                                        });
                                    });
                                });
                            });
                        });
                    });
                });
            });
        }
    }
}