using System;
using System.Collections;
using System.Collections.Generic;
using Peak.QuixelLogic.Scripts.Autogenerated;
using Peak.QuixelLogic.Scripts.Common;
using Peak.QuixelLogic.Scripts.Game.Gameplay;
using Peak.QuixelLogic.Scripts.ScenesLogic;
using Peak.QuixelLogic.Scripts.Settings;
using UnityEngine;

namespace Peak.QuixelLogic.Scripts.Game.FtueGameplay
{
    public class FtueGame_4 : MonoBehaviour
    {
        public void StartGame(Player player,
                                  RuleSettings selectedRuleset,
                                  FtueController ftueController,
                                  SessionScript sessionScript,
                                  OverlayUISceneActivator overlayUISceneActivator)
        {
            print("[FTUE] Fifth ftue game started ");

            InterfaceController.Instance.Show(GameWindow.OverlayUIScene);
            InterfaceController.Instance.Hide(GameWindow.MainMenu);

            SceneActivationBehaviour<TopBarUIActivator>.Instance.SetButtons(false);

            GameplayScript gameplay = sessionScript.CreateGameAndStart(player, selectedRuleset);
            BoardCreationScript boardCreationScript = gameplay.GetComponent<BoardCreationScript>();

            InterfaceController.Instance.Show(GameWindow.BonusBarUI);
            SceneActivationBehaviour<BonusBarUIActivator>.Instance.ShowDim(true);

            InterfaceController.Instance.Hide(GameWindow.ToolbarUI);

            boardCreationScript.BlockAllCells();

            overlayUISceneActivator.ShowFtueGameplayMessage(GameConstants.Ftue.FourthGame.FtueMessages.Instructions4_1, true, true, 0, true);

            ftueController.SendFtueProgress("Game4StartStarBar_27");

            overlayUISceneActivator.SubscribeForFullScreenTap(() =>
            {
                SceneActivationBehaviour<BonusBarUIActivator>.Instance.ShowDim(false);

                ftueController.SendFtueProgress("ReadyStart_28");
                overlayUISceneActivator.ShowFtueGameplayMessage(GameConstants.Ftue.FourthGame.FtueMessages.Instructions4_2, true, true, 0, true);

                overlayUISceneActivator.SubscribeForFullScreenTap(() =>
                {
                    ftueController.SendFtueProgress("StartGame4_29");

                    overlayUISceneActivator.HideFtueMessages();

                    overlayUISceneActivator.ftueMessagesPerStage = 0;
                    gameplay.StartDelayedSession();

                    boardCreationScript.UnblockAllCells();

                    gameplay.OnPuzzleSolved += gameData =>
                    {
                        int i = int.Parse(gameData.Ruleset.Id);
                        ftueController.ProceedToGameOverAward(player, i);

                        ftueController.SendFtueProgress("Game4Complete_30");
                    };
                });
            });
        }
    }
}