using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Peak.QuixelLogic.Scripts.ScenesLogic;
using Peak.QuixelLogic.Scripts.Game;
using Peak.QuixelLogic.Scripts.Settings.Autogenerated;
using System;

namespace Peak.QuixelLogic.Scripts.Common
{
    public sealed class PostGameCanvasAnimation : MonoBehaviour
    {
        public void AwardCoins()
        {
            //int playerCoins = SceneActivationBehaviour<GameLogicActivator>.Instance.GameController.Player.Coins;
            SceneActivationBehaviour<PostGameSceneActivator>.Instance.ShowCoinGrantAnimation();
        }

        public void ShowBannerStars()
        {
            SceneActivationBehaviour<PostGameSceneActivator>.Instance.ShowScoreBanner();
        }

        public void TriggerExitOfUIElement(int i) // 0 = character, 1 = toolbar, 2 = board, 3 = bonus bar, 4 = top bar
        {
            switch (i)
            {
                case 0:
                    SceneActivationBehaviour<BoardUIActivator>.Instance.ExitAlien();
                    break;

                case 1:
                    SceneActivationBehaviour<ToolbarUIActivator>.Instance.ExitToolbar();
                    break;

                case 2:
                    SceneActivationBehaviour<BoardUIActivator>.Instance.ExitBoard();
                    break;

                case 3:
                    SceneActivationBehaviour<BonusBarUIActivator>.Instance.ExitBonusBar();
                    break;

                case 4:
                    SceneActivationBehaviour<TopBarUIActivator>.Instance.ExitTopbar();
                    SceneActivationBehaviour<BoardUIActivator>.Instance.SendBoardToPostGame();
                    break;
            }
        }

        public void AlienUFOCelebration()
        {
            SceneActivationBehaviour<PostGameSceneActivator>.Instance.CelebrateAlien();
        }

        public void BoardAlienCelebration()
        {
            SceneActivationBehaviour<BoardUIActivator>.Instance.AlienCelebrateTrigger(postGame: true);
        }
    }
}