using System.Collections;
using System.Collections.Generic;
using JetBrains.Annotations;
using Peak.QuixelLogic.Scripts.Settings.Autogenerated;
using UnityEngine;

namespace Peak.QuixelLogic.Scripts.Common
{
    public class TopBannerScript : MonoBehaviour
    {
        [UsedImplicitly]
        public void LaunchStarOne()
        {
            SoundController.Instance.PlayAudioClip(SoundSettingsKey.Starappear);
            iOSHapticFeedback.OnSelection();
        }

        [UsedImplicitly]
        public void LaunchStarTwo()
        {
            SoundController.Instance.PlayAudioClip(SoundSettingsKey.Starappear);
            iOSHapticFeedback.OnSelection();
        }

        [UsedImplicitly]
        public void LaunchStarThree()
        {
            SoundController.Instance.PlayAudioClip(SoundSettingsKey.Starappear);
            iOSHapticFeedback.OnSelection();
        }
    }
}