using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Peak.QuixelLogic.Scripts.Common;
using Peak.QuixelLogic.Scripts.Autogenerated;
using TMPro;

namespace Peak.QuixelLogic.Scripts.ScenesLogic
{
    public class CollectionOverlayActivator : SceneActivationBehaviour<CollectionOverlayActivator>
    {
        public override void Initialize()
        {
            base.Initialize();
        }

        public override void Show()
        {
            base.Show();
        }

        public override void Hide()
        {
            base.Hide();
        }

        [SerializeField]
        private Animator collectionOverlayAnimator;

        [SerializeField]
        private Animator collectionAlien;

        [SerializeField]
        private TextMeshProUGUI messageText;

        [SerializeField]
        private GameObject CoinImage;

        [SerializeField]
        private GameObject CoinText;

        public void ShowCollectionViewAlien(string message, bool hideCoins = false)
        {
            Show();

            messageText.text = message;

            CoinImage.SetActive(!hideCoins);
            CoinText.SetActive(!hideCoins);

            collectionOverlayAnimator.gameObject.SetActive(true);
            collectionOverlayAnimator.SetTrigger("Celebrate");

            //collectionUfoObject.gameObject.SetActive(true);
            //fireworksHolder.SetActive(true);
            //collectionUfoObject.SetTrigger("GoldsUnlocked");
        }

        public void CelebrateAlien()
        {
            collectionAlien.SetTrigger("Celebrate");
        }

        public void HideCollectionViewAlien()
        {
            collectionOverlayAnimator.gameObject.SetActive(false);

            //collectionUfoObject.gameObject.SetActive(false);
            //fireworksHolder.SetActive(false);
            Hide();
        }
    }
}
