using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Peak.QuixelLogic.Scripts.Common;
using Peak.QuixelLogic.Scripts.Autogenerated;
using TMPro;
using System;

namespace Peak.QuixelLogic.Scripts.ScenesLogic
{
    public class PopupGameCompleteActivator : SceneActivationBehaviour<PopupGameCompleteActivator>
    {
        [SerializeField]
        private GameObject popupWindow;

        [SerializeField]
        private TextMeshProUGUI popupMessage;

        [SerializeField]
        private string completeMessage;

        private Action popupAccepted;

        public override void Initialize()
        {
            base.Initialize();
        }

        public override void Show()
        {
            base.Show();
            SceneActivationBehaviour<UICoinCounterActivator>.Instance.SetButtons(false);
            SoundController.Instance.PlayAudioClip(Settings.Autogenerated.SoundSettingsKey.Popupappear);
        }

        public override void Hide()
        {
            base.Hide();
            SceneActivationBehaviour<UICoinCounterActivator>.Instance.SetButtons(!InterfaceController.Instance.IsAnyPopupSceneActive());
        }

        public void ShowGameCompletePopup(Action accepted)
        {
            popupAccepted = accepted;

            popupMessage.text = completeMessage;
            popupWindow.SetActive(true);

            Show();
        }

        public void CloseWindow()
        {
            popupAccepted?.Invoke();
            popupWindow.SetActive(false);
            Hide();
        }
    }
}