using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Peak.QuixelLogic.Scripts.Common;
using Peak.QuixelLogic.Scripts.Autogenerated;
using JetBrains.Annotations;
using System;

namespace Peak.QuixelLogic.Scripts.ScenesLogic
{
    public class PopUpGdprActivator : SceneActivationBehaviour<PopUpGdprActivator>
    {
        public Action GDPRAccepted;

        public override void Initialize()
        {
            base.Initialize();
        }

        public override void Show()
        {
            base.Show();
            SoundController.Instance.PlayAudioClip(Settings.Autogenerated.SoundSettingsKey.Popupappear);
        }

        public override void Hide()
        {
            base.Hide();
        }

        public void ShowGDPRPopup(Action hasBeenAccepted)
        {
            Show();
            GDPRAccepted = hasBeenAccepted;
        }

        public void TermsButtonHandler()
        {
            Application.OpenURL("https://terms.brainbowgames.com/");
        }

        public void PrivacyButtonHandler()
        {
            Application.OpenURL("https://privacy.brainbowgames.com/");
        }

        [UsedImplicitly]
        public void AcceptButtonHandler()
        {
            InterfaceController.Instance.Hide(GameWindow.CollectionScreen);

            GDPRAccepted?.Invoke();

            SceneActivationBehaviour<GameLogicActivator>.Instance.AdsController.GDPRAcceptance();
            SceneActivationBehaviour<GameLogicActivator>.Instance.FtueController.GdprAccepted();

            InterfaceController.Instance.Hide(GameWindow.PopUpGdpr);
            InterfaceController.Instance.Unload(GameWindow.PopUpGdpr);
        }
    }
}