using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Peak.QuixelLogic.Scripts.Common;
using Peak.QuixelLogic.Scripts.Autogenerated;
using System;
using JetBrains.Annotations;
using Peak.QuixelLogic.Scripts.Common.AnalyticsScripts;
using Peak.QuixelLogic.Scripts.Game;
using Peak.QuixelLogic.Scripts.Settings;
using TMPro;

namespace Peak.QuixelLogic.Scripts.ScenesLogic
{
    public sealed class PopUpAndroidReviewActivator : SceneActivationBehaviour<PopUpAndroidReviewActivator>
    {

        public override void Initialize()
        {
            base.Initialize();
        }

        public override void Show()
        {
            base.Show();
            SceneActivationBehaviour<UICoinCounterActivator>.Instance.SetButtons(false);
        }

        public override void Hide()
        {
            base.Hide();
            SceneActivationBehaviour<UICoinCounterActivator>.Instance.SetButtons(!InterfaceController.Instance.IsAnyPopupSceneActive());
        }

        public void CloseButtonHandler()
        {
            InterfaceController.Instance.Hide(GameWindow.PopUpAndroidReview);
        }

        public void ReviewButtonHandler()
        {
            string url = ("market://details?id=" + Application.identifier);
            Application.OpenURL(url);
            InterfaceController.Instance.Hide(GameWindow.PopUpAndroidReview);
        }
    }
}