using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Peak.QuixelLogic.Scripts.Common;
using Peak.QuixelLogic.Scripts.Autogenerated;
using TMPro;
using Peak.QuixelLogic.Scripts.Settings;
using Peak.QuixelLogic.Scripts.Game;

namespace Peak.QuixelLogic.Scripts.ScenesLogic
{
    public class UILevelProgressCounterActivator : SceneActivationBehaviour<UILevelProgressCounterActivator>
    {
        [SerializeField]
        private TextMeshProUGUI levelProgressText;

        [SerializeField]
        private GlobalSettings globalSettings;

        public override void Initialize()
        {
            base.Initialize();
        }

        public override void Show()
        {
            base.Show();
        }

        public override void Hide()
        {
            base.Hide();
        }

        public void SetLevelProgress(Player player)
        {
            levelProgressText.text = player.CompletedLevels + "/" + globalSettings.LevelOrderSettings.RuleSettings.Length;
        }
    }
}
