/////////////////////////////////////////////////////////
/////////DO NOT MODIFY THIS AUTOGENERATED FILE///////////
///////////////////////////////////////////////////////// 
using System;
using System.Collections.Generic;

// ReSharper disable InconsistentNaming
namespace Peak.UnityGameFramework.Scripts.Autogenerated
{
    [Serializable]
    public enum GameWindow
    {
        NoWindow = 0,
        GlobalLogic = 1,
        LoadingMenu = 2,
        StartGame = 3,
        OverlayUIScene = 4,
        RootGameScene = 5,
        //GAME
        PauseMenu = 6,
        //SPE
        SPEGame = 7,
        WPAGame = 8,
        DebugScene = 9,
    }

    public static class GameWindowNames
    {
        public static readonly Dictionary<GameWindow, string> Mapping = new Dictionary<GameWindow, string>
        {
            { GameWindow.NoWindow , "NoWindow" },
            { GameWindow.GlobalLogic , "GlobalLogic" },
            { GameWindow.LoadingMenu , "LoadingMenu" },
            { GameWindow.StartGame , "StartGame" },
            { GameWindow.OverlayUIScene , "OverlayUIScene" },
            { GameWindow.RootGameScene, "RootGameScene" },
            { GameWindow.PauseMenu , "PauseMenu" },
            { GameWindow.SPEGame, "SPEGame" },
            { GameWindow.WPAGame, "WPAGame" },
            { GameWindow.DebugScene, "DebugScene" }
        };
    }
}