using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Peak.Speedoku.Scripts.Common;
using Peak.Speedoku.Scripts.Autogenerated;
using System;
using UnityEngine.UI;
using UI.Pagination;

namespace Peak.Speedoku.Scripts.ScenesLogic
{
    public class TutorialPopupActivator : SceneActivationBehaviour<TutorialPopupActivator> 
    {
        public Button closeButton;
        [SerializeField] private PagedRect pagedRect;

        public override void Initialize()
        {
            base.Initialize();
        }

        public override void Show(bool animated = false)
        {
            base.Show(animated);
            pagedRect.SetCurrentPage(1);
        }

        public override void Hide()
        {
            base.Hide();
        }

        public void CloseButtonHandler()
        {
            InterfaceController.Instance.Hide(GameWindow.TutorialPopup);
            LocalisationController.Instance.PlayAudioClip(Settings.Autogenerated.SoundSettingsKey.PopupSound);
        }
    }
}
