using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Peak.UnityGameFramework.Scripts.Common;
using Peak.UnityGameFramework.Scripts.Autogenerated;
using Peak.UnityGameFramework.Scripts.ScenesLogic;
using TMPro;
namespace Peak.Speedoku.Scripts.ScenesLogic
{
    public class DebugActivator : SceneActivationBehaviour<DebugActivator>
    {
        [SerializeField] TMP_Dropdown gameType;
        [SerializeField] TMP_Dropdown difficultyType;

        public override void Initialize()
        {
            base.Initialize();
        }

        public override void Show(bool animated = false)
        {
            base.Show(animated);
        }

        public override void Hide()
        {
            base.Hide();
        }

        //public override void SetButtonsEnabled(bool isEnabled)
        //{
            //base.SetButtonsEnabled(isEnabled);
        //}

        public void StartPressed()
        {
            print($"[DEBUG] SELECTED PRESSED - game: {gameType.options[gameType.value].text} - difficulty: {difficultyType.value}");
            SceneActivationBehaviour<RootGameSceneActivator>.Instance.LoadGame("WPA");
            SceneActivationBehaviour<RootGameSceneActivator>.Instance.StartRound(difficultyType.value);
            //StartCoroutine(DelayedStart());
        }

        private IEnumerator DelayedStart()
        {
            yield return new WaitForSeconds(1);

            print("WPA Loaded - start round");
            SceneActivationBehaviour<RootGameSceneActivator>.Instance.StartRound(difficultyType.value);
        }
    }
}
