using System;
using System.Collections.Generic;
using Peak.QuixelLogic.Scripts.Autogenerated;
using Peak.QuixelLogic.Scripts.Common.Localisation;
using Peak.QuixelLogic.Scripts.Game.Gameplay;
using UnityEngine;
using UnityEngine.Serialization;

namespace Peak.QuixelLogic.Scripts.Settings
{
    public sealed class LevelGroupingSettings : ScriptableObject
    {
        [Header("Level group ID.")]
        public string Id;

        [Space]

        [Header("Level group name e.g. Forest.")]
        public string CollectionNameKey;

        [Space]

        public bool Locked;

        [Space]

        public Sprite LevelCardSprite;

        [Space]

        [Tooltip("Game board background image")]
        public Sprite boardBackgroundImage;

        [Tooltip("Main menu background image")]
        public Sprite MainMenuBackgroundImage;

        [Space]

        public int UnlockCoinReward;

        [Space]

        [Header("Levels - in groups of 3.")]
        public List<RuleSettings> Levels = new List<RuleSettings>();

        [Space]

        [Header("GOLD levels.")]
        public List<RuleSettings> GoldLevels = new List<RuleSettings>();

        [Space]

        public GameObject CollectionPrefab;

        public void Init(string ID, bool locked, Sprite levelCard, Sprite background, Sprite backgroundMain)
        {
            Id = ID;
            Locked = locked;
            LevelCardSprite = levelCard;
            boardBackgroundImage = background;
            MainMenuBackgroundImage = backgroundMain;
        }
    }
}