using System;
using Peak.QuixelLogic.Scripts.Autogenerated;
using Peak.QuixelLogic.Scripts.Game.Gameplay;
using UnityEngine;
using UnityEngine.Serialization;

namespace Peak.QuixelLogic.Scripts.Settings
{
    public class LevelOrderSettings : ScriptableObject
    {
        [Header("Levels (You can 'Shift+DEL' to remove a row from a list)")]
        public RuleSettings[] RuleSettings;
    }
}