using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Peak.QuixelLogic.Scripts.ScenesLogic;
using Peak.QuixelLogic.Scripts.Settings.Autogenerated;

namespace Peak.QuixelLogic.Scripts.Game
{
    public class StarProjectileScript : MonoBehaviour
    {
        //private Transform target;

        //[SerializeField]
        //private GameObject starImage;

        //private bool hitTarget = false;
        //private float rotate = 0;
        //private float scale = 0;

        //private void Start()
        //{
        //    target = GameObject.Find("ProgressBar").transform;
        //}

        //private void FixedUpdate()
        //{
        //    float distance = Vector3.Distance(transform.position, target.position);
        //    bool close = distance < 10 ? true : false;
        //    rotate += 0.5f;

        //    starImage.transform.Rotate(0, 0, rotate);

        //    // The step size is equal to speed times frame time.
        //    float step = Time.deltaTime * (close ? 30 : 50);

        //    // Move our position a step closer to the target.
        //    transform.position = Vector3.MoveTowards(transform.position, target.position, step);

        //    if (Vector3.Distance(transform.position, target.position) < 5f)
        //    {
        //        Mathf.Clamp(scale -= 0.1f, 1.2f, 0);
        //        starImage.transform.localScale = new Vector3(scale, scale, scale);
        //    }
        //    else
        //    {
        //        Mathf.Clamp(scale += 0.1f, 0, 1.2f);
        //        starImage.transform.localScale = new Vector3(scale, scale, scale);
        //    }

        //    if (Vector3.Distance(transform.position, target.position) < 0.1f && scale < 0.25f)
        //    {
        //        if (!hitTarget)
        //        {
        //            SceneActivationBehaviour<PostGameSceneActivator>.Instance.IncrementProgressBar();
        //            hitTarget = true;
        //        }

        //        Destroy(gameObject, 0.1f);
        //        return;
        //    }
        //}

        //private void OnDestroy()
        //{
        //    LocalisationController.Instance.PlayAudioClip(SoundSettingsKey.Stararrives);
        //}
    }
}